name: Validation

on:
  pull_request:
    paths:
      - "domains/*"
      - "tests/*"
      - "utils/*"
      - ".github/workflows/validation.yml"
      - "dnsconfig.js"
  push:
    branches: [main]
    paths:
      - "domains/*"
      - "tests/*"
      - "utils/*"
      - ".github/workflows/validation.yml"
      - "dnsconfig.js"
  workflow_dispatch:

concurrency:
  group: validation-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  dns:
    name: DNS
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Check DNS
        uses: DNSControl/dnscontrol-action@main
        with:
          cmdargs: check
          dnsconfig_file: "dnsconfig.js"

  json:
    name: JSON
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: JSON Syntax Check
        uses: limitusus/json-syntax-check@v2
        with:
          pattern: "\\.json$"
        env:
          BASE: "domains/"

  tests:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - run: npm install
      - run: npm test
